### ISSUE TITLE
Trellis tutorial might need a note about the "WordPress installed" email

### ISSUE THREAD

**Issue by ryagas** [dreamhost/dreamcloud-docs#86]
Found this out while following the tutorial for Trellis. At the "vagrant up" step, it errors out at the "TASK [wordpress-install : Install WP]" section as follows:

```
TASK [wordpress-install : Install WP] ******************************************
System info:
  Ansible 2.1.1.0; Vagrant 1.8.5; Darwin
  Trellis 0.9.8: August 14th, 2016
---------------------------------------------------
PHP Fatal error:  Uncaught phpmailerException: Invalid address:
wordpress@${http_host} in /srv/www/example.com/current/web/wp/wp-includes
/class-phpmailer.php:946
Stack trace:
#0 /srv/www/example.com/current/web/wp/wp-includes/pluggable.php(352):
PHPMailer->setFrom('wordpress@${htt...', 'WordPress')
#1 /srv/www/example.com/current/web/wp/wp-admin/includes/upgrade.php(392):
wp_mail('something@examp...', 'New WordPress S...', 'Your new WordPr...')
#2 /srv/www/example.com/current/web/wp/wp-admin/includes/upgrade.php(95):
wp_new_blog_notification('example.com', 'http://${HTTP_H...', 1, 'The
password yo...')
#3 phar:///usr/bin/wp/php/commands/core.php(763): wp_install('example.com',
'ryan', 'something@examp...', true, '', 'XXXXXXXXXX')
#4 phar:///usr/bin/wp/php/commands/core.php(573):
Core_Command->_install(Array)
#5 [internal function]: Core_Command->install(Array, Array)
#6 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67):
call_user_func(Array, Array, Array)
#7 [internal function]: WP_CLI\Dispatcher\CommandFactory:: in
/srv/www/example.com/current/web/wp/wp-includes/class-phpmailer.php on line
946
failed: [default] (item=example.com) => {"changed": true, "cmd": ["wp", "core", "install", "--allow-root", "--url=http://${HTTP_HOST}", "--title=example.com", "--admin_user=ryan", "--admin_password=XXXXXXXXXX", "--admin_email=something@example.com"], "delta": "0:00:12.668928", "end": "2016-08-18 22:48:30.257855", "failed": true, "item": "example.com", "rc": 255, "start": "2016-08-18 22:48:17.588927", "stderr": "PHP Fatal error:  Uncaught phpmailerException: Invalid address: wordpress@${http_host} in /srv/www/example.com/current/web/wp/wp-includes/class-phpmailer.php:946\nStack trace:\n#0 /srv/www/example.com/current/web/wp/wp-includes/pluggable.php(352): PHPMailer->setFrom('wordpress@${htt...', 'WordPress')\n#1 /srv/www/example.com/current/web/wp/wp-admin/includes/upgrade.php(392): wp_mail('something@examp...', 'New WordPress S...', 'Your new WordPr...')\n#2 /srv/www/example.com/current/web/wp/wp-admin/includes/upgrade.php(95): wp_new_blog_notification('example.com', 'http://${HTTP_H...', 1, 'The password yo...')\n#3 phar:///usr/bin/wp/php/commands/core.php(763): wp_install('example.com', 'ryan', 'something@examp...', true, '', 'XXXXXXXXXX')\n#4 phar:///usr/bin/wp/php/commands/core.php(573): Core_Command->_install(Array)\n#5 [internal function]: Core_Command->install(Array, Array)\n#6 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)\n#7 [internal function]: WP_CLI\\Dispatcher\\CommandFactory:: in /srv/www/example.com/current/web/wp/wp-includes/class-phpmailer.php on line 946", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [common : restart memcached] ***********************************
changed: [default]

RUNNING HANDLER [common : reload php-fpm] **************************************
changed: [default]

RUNNING HANDLER [common : reload nginx] ****************************************
changed: [default]

RUNNING HANDLER [common : perform nginx reload] ********************************
changed: [default]

RUNNING HANDLER [fail2ban : restart fail2ban] **********************************
changed: [default]

RUNNING HANDLER [ferm : restart ferm] ******************************************
skipping: [default]

RUNNING HANDLER [ntp : restart ntp] ********************************************
changed: [default]

RUNNING HANDLER [sshd : restart ssh] *******************************************
changed: [default]
       	to retry, use: --limit @/Users/user/example.com/trellis/dev.retry

PLAY RECAP *********************************************************************
default                    : ok=102  changed=81   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

The VM is actually still running and accesible though. I don't see that mentioned at https://roots.io/trellis/docs/wordpress-sites/ either, so anyone following that would hit this issue  too and think it failed. It means no WordPress install email is sent, so it could be a problem when it comes time to deploy a fresh install.

**Comment by smaffulli** [comment]
Looks like the {http_host} variable is not getting set... but that variable is only referenced in wordpress-install, which is not part of this tutorial. I'm not sure why that fails. Shall we move this discussion to roots discourse?

**Comment by ryagas** [comment]
Found the bug (WP core bug), and patch:

https://core.trac.wordpress.org/ticket/37736

Roots is waiting for WP 4.61.
